// @generated — DO NOT EDIT.
// Produced by `cargo run --bin gen-types` from the desktop crate.
// Source: apps/desktop/src/bin/gen_types.rs (D-01).

// This file has been generated by Specta. Do not edit this file manually.
export type CodexKind = 'character' | 'place' | 'object' | 'note';

/**
 *  Position in the writing pipeline. New documents land in `Draft`;
 *  the user moves them through `Revised` → `Final`. `Trashed` is a soft
 *  delete that still lives in storage so the user can recover it.
 */
export type DocumentStatus = 'draft' | 'revised' | 'final' | 'trashed';

export type DocumentType = 'chapter' | 'scene' | 'note' | 'folder' | 'manga_page';

export type ProjectStatus = 'active' | 'archived';
