/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/AppShell.vue')['default']
    BibliographyDialog: typeof import('./components/BibliographyDialog.vue')['default']
    Binder: typeof import('./components/Binder.vue')['default']
    CitationPickerDialog: typeof import('./components/CitationPickerDialog.vue')['default']
    CodexEntryCard: typeof import('./components/CodexEntryCard.vue')['default']
    CodexEntryDialog: typeof import('./components/CodexEntryDialog.vue')['default']
    CodexRefPickerDialog: typeof import('./components/CodexRefPickerDialog.vue')['default']
    ExportDialog: typeof import('./components/ExportDialog.vue')['default']
    FindReplaceBar: typeof import('./components/FindReplaceBar.vue')['default']
    GoalProgress: typeof import('./components/GoalProgress.vue')['default']
    Inspector: typeof import('./components/Inspector.vue')['default']
    KeybindingsEditor: typeof import('./components/KeybindingsEditor.vue')['default']
    NewProjectWizard: typeof import('./components/NewProjectWizard.vue')['default']
    OnboardingDialog: typeof import('./components/OnboardingDialog.vue')['default']
    PomodoroWidget: typeof import('./components/PomodoroWidget.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    ProjectViewToggle: typeof import('./components/ProjectViewToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveAsTemplateDialog: typeof import('./components/SaveAsTemplateDialog.vue')['default']
    SaveIndicator: typeof import('./components/SaveIndicator.vue')['default']
    ScriveningsView: typeof import('./components/ScriveningsView.vue')['default']
    SearchDialog: typeof import('./components/SearchDialog.vue')['default']
    SnapshotsList: typeof import('./components/SnapshotsList.vue')['default']
    SwitchProjectDialog: typeof import('./components/SwitchProjectDialog.vue')['default']
    WizardStepConfirm: typeof import('./components/WizardStepConfirm.vue')['default']
    WizardStepMetadata: typeof import('./components/WizardStepMetadata.vue')['default']
    WizardStepTemplate: typeof import('./components/WizardStepTemplate.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
