/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/AppShell.vue')['default']
    Binder: typeof import('./components/Binder.vue')['default']
    ExportDialog: typeof import('./components/ExportDialog.vue')['default']
    Inspector: typeof import('./components/Inspector.vue')['default']
    NewProjectWizard: typeof import('./components/NewProjectWizard.vue')['default']
    OnboardingDialog: typeof import('./components/OnboardingDialog.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveIndicator: typeof import('./components/SaveIndicator.vue')['default']
    SnapshotsList: typeof import('./components/SnapshotsList.vue')['default']
    SwitchProjectDialog: typeof import('./components/SwitchProjectDialog.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
